sculpin_content_types:
    posts:
        permalink: :year-:month-:day-:filename/

services:
    twig.extension.intl:
        class: Twig\Extra\Intl\IntlExtension
        tags:
            - { name: twig.extension }

# To disable posts (e.g., if you aren't planning on having any posts and Sculpin's watch mode complains):
#sculpin_content_types:
#    posts:
#        enabled: false
